#!/usr/bin/env bash
# =============================================================================
# dump-osm-subset.sh
#
# Dumps a small subset of the production OSM sync database into a local SQL
# file that can be loaded into the test osm_database container.
#
# Currently dumps: Berlin (kreisfreie Stadt) + Kreis Segeberg (Landkreis).
# Both are scored admin areas (admin_level 4 / 6), so the dump is directly
# usable for testing the scoring pipeline.
#
# Prerequisites:
#   1. kubectl port-forward to the OSM sync DB running on localhost:5433
#      (see a11yscore-experiments README for instructions)
#   2. psql client installed
#
# Usage:
#   ./scripts/dump-osm-subset.sh
#
# Output:
#   docker/osm-subset-data.sql
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$PROJECT_DIR/docker/osm-subset-data.sql"

# ── Connection (production OSM sync DB via port-forward) ─────────────────────

DB_HOST="${NITRO_DATABASE_OSM_SYNC_HOST:-localhost}"
DB_PORT="${NITRO_DATABASE_OSM_SYNC_PORT:-5433}"
DB_USER="${NITRO_DATABASE_OSM_SYNC_USER:-imposm}"
DB_NAME="${NITRO_DATABASE_OSM_SYNC_DB:-imposm}"

if [ -z "${PGPASSWORD:-}" ] && [ -f "$PROJECT_DIR/.env" ]; then
  PGPASSWORD=$(grep '^NITRO_DATABASE_OSM_SYNC_PASSWORD=' "$PROJECT_DIR/.env" | cut -d= -f2-)
  export PGPASSWORD
fi

# Force every psql session to be read-only with a generous timeout so a bad
# spatial join cannot run forever against production.
export PGOPTIONS="-c default_transaction_read_only=on -c statement_timeout=1800000"

PSQL=(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -v ON_ERROR_STOP=1)

echo "Connecting to OSM sync DB at $DB_HOST:$DB_PORT/$DB_NAME (read-only)"
echo "Output: $OUTPUT"
echo ""

# ── Verify connection before doing anything ──────────────────────────────────

if ! "${PSQL[@]}" -c "SELECT 1;" > /dev/null 2>&1; then
  echo "ERROR: Cannot connect to $DB_HOST:$DB_PORT/$DB_NAME."
  echo "       Is the kubectl port-forward running?"
  exit 1
fi

# ── Admin areas to dump ───────────────────────────────────────────────────────
# Read from the shared regions.json used by a11yscore-experiments.
# Falls back to a small default set if the file is not found.

REGIONS_FILE="${REGIONS_FILE:-$(cd "$SCRIPT_DIR" && realpath ../../a11yscore-experiments/src/data/scoring/regions.json 2>/dev/null || echo "")}"

if [ -n "$REGIONS_FILE" ] && [ -f "$REGIONS_FILE" ]; then
  echo "Reading regions from $REGIONS_FILE"
  # Extract osm_id values with lightweight grep/sed (no jq dependency)
  ADMIN_OSM_IDS=$(grep '"osm_id"' "$REGIONS_FILE" | sed -E 's/.*"osm_id": *(-?[0-9]+).*/\1/' | paste -sd, -)
else
  echo "Regions file not found, using default (Berlin + Aschaffenburg)"
  ADMIN_OSM_IDS="-62422, -62532"
fi

echo "Admin OSM IDs: $ADMIN_OSM_IDS"

# Seconds to sleep between tables to avoid overloading the DB
THROTTLE_SECS="${THROTTLE_SECS:-2}"

TABLES=(osm_admin osm_admin_gen0 osm_admin_gen1 osm_amenities osm_platforms osm_stations)

# ── File header ──────────────────────────────────────────────────────────────

cat > "$OUTPUT" <<'HEADER'
-- =============================================================================
-- OSM data subset: Berlin + Kreis Segeberg
-- Generated by scripts/dump-osm-subset.sh
--
-- Load into a PostGIS database that already has the osm_database-schema.sql:
--   PGPASSWORD=imposm psql -h localhost -p 54322 -U imposm -d imposm \
--     -f docker/osm-subset-data.sql
-- =============================================================================
SET session_replication_role = 'replica';
SET client_min_messages = 'warning';

HEADER

# ── Dump each table, spatially filtered ──────────────────────────────────────
# Uses EXISTS + spatial index join instead of ST_Union to avoid building a
# massive combined geometry that kills performance with many regions.

for TABLE in "${TABLES[@]}"; do
  echo -n "  $TABLE … "

  COUNT=$("${PSQL[@]}" --no-align --tuples-only -c "
    SELECT count(*)
    FROM $TABLE t
    WHERE EXISTS (
      SELECT 1 FROM osm_admin a
      WHERE a.osm_id IN ($ADMIN_OSM_IDS)
        AND ST_Intersects(t.geometry, a.geometry)
    )
  ")
  echo "$COUNT rows"

  {
    echo "-- $TABLE ($COUNT rows)"
    echo "\\echo 'Loading $TABLE ($COUNT rows)…'"
    echo "COPY $TABLE FROM stdin;"
    "${PSQL[@]}" -c "
      COPY (
        SELECT DISTINCT ON (t.ctid) t.*
        FROM $TABLE t
        WHERE EXISTS (
          SELECT 1 FROM osm_admin a
          WHERE a.osm_id IN ($ADMIN_OSM_IDS)
            AND ST_Intersects(t.geometry, a.geometry)
        )
      ) TO STDOUT
    "
    echo "\\."
    echo ""
  } >> "$OUTPUT"

  # Throttle between tables to avoid overloading the production DB
  if [ "$TABLE" != "${TABLES[${#TABLES[@]}-1]}" ]; then
    echo "  (sleeping ${THROTTLE_SECS}s…)"
    sleep "$THROTTLE_SECS"
  fi
done

# ── Footer ───────────────────────────────────────────────────────────────────

cat >> "$OUTPUT" <<'FOOTER'
SET session_replication_role = 'origin';
\echo 'Done loading OSM subset data.'
FOOTER

echo ""
echo "Done! → $OUTPUT"
echo ""
echo "To use:"
echo "  1. docker compose up osm_database_test -d"
echo "  2. PGPASSWORD=imposm psql -h localhost -p 54322 -U imposm -d imposm -f docker/osm_database-schema.sql"
echo "  3. PGPASSWORD=imposm psql -h localhost -p 54322 -U imposm -d imposm -f docker/osm-subset-data.sql"
echo "  4. PGPASSWORD=imposm psql -h localhost -p 54322 -U imposm -d imposm -f docker/scoring-config-schema-and-seed.sql"

